name: Cron
on:
  push:
    branches: main
  schedule:
  - cron: '38 0 * * *'
  workflow_dispatch:
concurrency: cron
defaults:
  run:
    shell: bash
env:
  PYTHONUNBUFFERED: '1'
jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
    steps:
    - uses: zhangyoufu/actions/checkout@main
      timeout-minutes: 1

    - name: Looking for new downloads and upload as release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: ./check.py

    - name: Commit if dirty
      if: ${{ always() }}
      run: |-
        [ -z "$(git status --porcelain)" ] && exit 0
        git add state.txt
        git commit -m '[gh-actions] update state'
        git push origin HEAD:main
